'use strict';

 exports.BattlePokedex = {
  fletchinder: {
		num: 662,
		species: "Fletchinder",
		types: ["Fire","Flying"],
		baseStats: {hp: 62, atk: 73, def: 55, spa: 56, spd: 52, spe: 84},
		abilities: {0: "Flame Body", H: "Gale Wings"},
		heightm: 0.7,
		weightkg: 16,
		color: "Red",
		prevo: "fletchling",
		evos: ["talonflame","talonfey","talonwave","talonacid","talondrake","talonvolt"],
		evoLevel: 17,
		eggGroups: ["Flying"],
  },
  talonfey: {
      		num: 9001,
      		species: "Talonfey",
      		types: ["Fairy","Flying"],
      		baseStats: {hp: 81, atk: 126, def: 71, spa: 69, spd: 74, spe: 78},
      		abilities: {0: "Dazzling", H: "Gale Wings"},
      		prevo: "fletchinder",
  },
  talonwave: {
      		num: 9002,
      		species: "Talonwave",
      		types: ["Water","Flying"],
      		baseStats: {hp: 126, atk: 71, def: 78, spa: 81, spd: 74, spe: 69},
      		abilities: {0: "Water Absorb", H: "Gale Wings"},
      		prevo: "fletchinder",
  },
  talonacid: {
      		num: 9003,
      		species: "Talonacid",
     		types: ["Poison","Flying"],
      		baseStats: {hp: 74, atk: 69, def: 126, spa: 78, spd: 81, spe: 71},
      		abilities: {0: "Poison Point", H: "Corrosion"},
      		prevo: "fletchinder",
  },
  talondrake: {
      		num: 9004,
      		species: "Talondrake",
     		types: ["Dragon","Flying"],
      		baseStats: {hp: 78, atk: 81, def: 74, spa: 126, spd: 69, spe: 71},
      		abilities: {0: "Tough Claws", H: "Gale Wings"},
      		prevo: "fletchinder",
  },
  talonvolt: {
      		num: 9005,
      		species: "Talonvolt",
      		types: ["Electric","Flying"],
      		baseStats: {hp: 69, atk: 74, def: 71, spa: 126, spd: 78, spe: 81},
      		abilities: {0: "Static", H: "Gale Wings"},
      		prevo: "fletchinder",
  },
  raichu: {
		num: 26,
		species: "Raichu",
		types: ["Electric"],
		baseStats: {hp: 60, atk: 90, def: 55, spa: 90, spd: 80, spe: 110},
		abilities: {0: "Static", H: "Lightning Rod"},
		heightm: 0.8,
		weightkg: 30,
		color: "Yellow",
		prevo: "pikachu",
		evoLevel: 1,
	        evos: ["umichu","armochu","miraclechu","noxiochu","keruchu","conflachu"],
		eggGroups: ["Field", "Fairy"],
		otherFormes: ["raichualola"],
  },
  umichu: {
	        num: 9006,
	        species: "Umichu",
	        types: ["Electric","Water"],
	        baseStats: {hp: 80, atk: 75, def: 110, spa: 90, spd: 115, spe: 80},
	        abilities: {0: "Hydration", H: "Lightning Rod"},
	        prevo: "Raichu"
  },
  armochu: {
	        num: 9007,
	        species: "Armochu",
	        types: ["Electric","Steel"],
	        baseStats: {hp: 89, atk: 55, def: 101, spa: 140, spd: 103, spe: 62},
	        abilities: {0: "Filter", H: "Battle Armour"},
	        prevo: "Raichu"
  },
  miraclechu: {
	        num: 9008,
	        species: "Miraclechu",
	        types: ["Electric","Psychic"],
	        baseStats: {hp: 60, atk: 90, def: 75, spa: 135, spd: 75, spe: 110},
	        abilities: {0: "Static", H: "Miracle Dash"},
	        prevo: "Raichu"
  },
  noxiochu: {
	        num: 9009,
	        species: "Noxiochu",
	        types: ["Electric","Poison"],
	        baseStats: {hp: 75, atk: 112, def: 50, spa: 91, spd: 86, spe: 136},
	        abilities: {0: "Volt Absorb", 1: "Poison Touch", H: "Electrojection"},
	        prevo: "Raichu"
  },
  keruchu: {
	        num: 9010,
	        species: "Keruchu",
	        types: ["Electric","Fighting"],
	        baseStats: {hp: 70, atk: 110, def: 85, spa: 95, spd: 60, spe: 130},
	        abilities: {0: "Scrappy", H: "Sheer Force"},
	        prevo: "Raichu"
  },
  conflachu: {
	        num: 9011,
	        species: "Conflachu",
	        types: ["Electric","Fire"],
	        baseStats: {hp: 110, atk: 130, def: 65, spa: 70, spd: 65, spe: 110},
	        abilities: {0: "Static", H: "Reckless"},
	        prevo: "Raichu"
  },
};
