'use strict';

exports.BattleLearnsets = {
gumshoosub: {learnset: {
		attract: ["7M"],
		bide: ["7L16"],
		bite: ["7L19"],
		block: ["7T"],
		bulldoze: ["7M"],
		confide: ["7M"],
		crunch: ["7L39"],
		doubleteam: ["7M"],
		dualchop: ["7T"],
		earthquake: ["7M"],
		echoedvoice: ["7M"],
		endeavor: ["7T"],
		facade: ["7M"],
		firepunch: ["7T"],
		fling: ["7M"],
		frustration: ["7M"],
		hiddenpower: ["7M"],
		hyperfang: ["7L43"],
		icepunch: ["7T"],
		ironhead: ["7T"],
		irontail: ["7T"],
		lastresort: ["7T"],
		leer: ["7L3", "7L1"],
		mudslap: ["7L23"],
		odorsleuth: ["7L13"],
		payback: ["7M"],
		protect: ["7M"],
		pursuit: ["7L7", "7L1"],
		return: ["7M"],
		roar: ["7M"],
		rocktomb: ["7M"],
		round: ["7M"],
		sandattack: ["7L10", "7L1"],
		sandstorm: ["7M"],
		scaryface: ["7L35"],
		shockwave: ["7T"],
		snore: ["7T"],
		stompingtantrum: ["7T"],
		substitute: ["7M"],
		superfang: ["7T", "7L27"],
		swagger: ["7M"],
		tackle: ["7L1"],
		takedown: ["7L31"],
		taunt: ["7M"],
		thief: ["7M"],
		thunderpunch: ["7T"],
		torment: ["7M"],
		toxic: ["7M"],
		uproar: ["7T"],
		uturn: ["7M"],
		workup: ["7M"],
		zenheadbutt: ["7T"],
    circlethrow: ["7L1"],
    stockpile: ["7L1"],
    swallow: ["7L1"],
    spitup: ["7L1"],
    headsmash: ["7L1"],
    stealthrock: ["7L1"],
    trumpcard: ["7L1"],
    finalgambit: ["7L1"],
	}},
  
  };
