'use strict';

exports.BattlePokedex = {
    pidgeyalola: {
        num: 16,
        species: "Pidgey-Alola",
        baseSpecies: "Pidgey",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 40,
            atk: 40,
            def: 40,
            spa: 45,
            spd: 35,
            spe: 51
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
		 weightkg: 1.8,
    },
        pidgeottoalola: {
        num: 17,
        species: "Pidgeotto-Alola",
        baseSpecies: "Pidgeotto",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 63,
            atk: 60,
            def: 55,
            spa: 60,
            spd: 50,
            spe: 61
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
		  weightkg: 30,
    },
     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
		  weightkg: 39.5,
    },
	     pidgeotalolamega: {
        num: 18,
        species: "Pidgeot-Alola-Mega",
        baseSpecies: "Pidgeot",
        forme: "Alola-Mega",
        formeLetter: "AM",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 120,
            def: 80,
            spa: 120,
            spd: 80,
            spe: 51
        },
        abilities: {0: "Adaptability"},
		  weightkg: 50.5,	  
    },
	   nidoranfalola: {
        num: 29,
        species: "Nidoran-F-Alola",
        baseSpecies: "Nidoran-F",
		  gender: "F",
        forme: "Alola",
        formeLetter: "A",
        types: ["Grass"],
        baseStats: { 
            hp: 35,
            atk: 57,
            def: 32,
            spa: 60,
            spd: 30,
            spe: 61
        },
        abilities: {0: "Chlorophyll", 1: "Leaf Guard", H: "Sheer Force"},
		  weightkg: 7,
    },
	    nidoranaalola: {
        num: 30,
        species: "Nidorana-Alola",
        baseSpecies: "Nidorana",
		  gender: "F",
        forme: "Alola",
        formeLetter: "A",
        types: ["Grass"],
        baseStats: { 
            hp: 50,
            atk: 72,
            def: 47,
            spa: 75,
            spd: 45,
            spe: 76
        },
        abilities: {0: "Chlorophyll", 1: "Leaf Guard", H: "Sheer Force"},
			 weightkg: 20,
    },
	   nidoqueenalola: {
        num: 31,
        species: "Nidoqueen-Alola",
        baseSpecies: "Nidoqueen",
        forme: "Alola",
        formeLetter: "A",
        types: ["Grass", "Fire"],
        baseStats: {
            hp: 60,
            atk: 85,
            def: 67,
            spa: 122,
            spd: 65,
            spe: 106
        },
        abilities: {0: "Chlorophyll", 1: "Drought", H: "Sheer Force"},
			weightkg: 60,
    },
	  nidoranmalola: {
        num: 32,
        species: "Nidoran-M-Alola",
        baseSpecies: "Nidoran-M",
        forme: "Alola",
        formeLetter: "A",
        types: ["Water"],
        baseStats: {
            hp: 36,
            atk: 57,
            def: 30,
            spa: 60,
            spd: 30,
            spe: 60
        },
        abilities: {0: "Swift Swim", 1: "Hydration", H: "Sheer Force"},
		  weightkg: 9,
    },
	     nidorinoalola: {
        num: 33,
        species: "Nidorino-Alola",
        baseSpecies: "Nidorino",
        forme: "Alola",
        formeLetter: "A",
        types: ["Water"],
        baseStats: {
            hp: 51,
            atk: 72,
            def: 47,
            spa: 75,
            spd: 45,
            spe: 75
        },
        abilities: {0: "Swift Swim", 1: "Hydration", H: "Sheer Force"},
		  weightkg: 19.5,
    },
	     nidokingalola: {
        num: 34,
        species: "Nidoking-Alola",
        baseSpecies: "Nidoking",
        forme: "Alola",
        formeLetter: "A",
        types: ["Water"],
        baseStats: {
            hp: 61,
            atk: 85,
            def: 67,
            spa: 122,
            spd: 65,
            spe: 105
        },
        abilities: {0: "Swift Swim", 1: "Drizzle", H: "Sheer Force"},
			  weightkg: 62,
    },
	     cleffaalola: {
        num: 173,
        species: "Cleffa-Alola",
        baseSpecies: "Cleffa",
        forme: "Alola",
        formeLetter: "A",
        types: ["Fire", "Fairy"],
		  baseStats: {hp: 50, atk: 25, def: 28, spa: 45, spd: 55, spe: 15},
        abilities: {0: "Magic Guard", 1: "Magic Bounce", H: "Telepathy"},
		  weightkg: 3,
    },
		  clefairylola: {
        num: 35,
        species: "Cleffa-Alola",
        baseSpecies: "Cleffa",
        forme: "Alola",
        formeLetter: "A",
        types: ["Fire", "Fairy"],
        baseStats: {hp: 70, atk: 45, def: 48, spa: 60, spd: 65, spe: 35},
        abilities: {0: "Magic Guard", 1: "Magic Bounce", H: "Telepathy"},
			  weightkg: 7.5,
    },
	     clefablelola: {
        num: 173,
        species: "Clefable-Alola",
        baseSpecies: "Clefable",
        forme: "Alola",
        formeLetter: "A",
        types: ["Fire", "Fairy"],
        baseStats: {hp: 95, atk: 70, def: 73, spa: 95, spd: 90, spe: 60},
        abilities: {0: "Magic Guard", 1: "Magic Bounce", H: "Telepathy"},
		  weightkg: 40,
    },
	     /* pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    }, */
    };
