'use strict';

exports.BattlePokedex = {
    pidgeyalola: {
        num: 16,
        species: "Pidgey-Alola",
        baseSpecies: "Pidgey",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 40,
            atk: 40,
            def: 40,
            spa: 45,
            spd: 35,
            spe: 51
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
		 weightkg: 1.8,
    },
        pidgeottoalola: {
        num: 17,
        species: "Pidgeotto-Alola",
        baseSpecies: "Pidgeotto",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 63,
            atk: 60,
            def: 55,
            spa: 60,
            spd: 50,
            spe: 61
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
		  weightkg: 30,
    },
     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
		  weightkg: 39.5,
    },
	     pidgeotalolamega: {
        num: 18,
        species: "Pidgeot-Alola-Mega",
        baseSpecies: "Pidgeot",
        forme: "Alola-Mega",
        formeLetter: "AM",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 120,
            def: 80,
            spa: 120,
            spd: 80,
            spe: 51
        },
        abilities: {0: "Adaptability"},
		  weightkg: 50.5,	  
    },
	  /*   nidoranfalola: {
        num: 18,
        species: "Nidoran-F-Alola",
        baseSpecies: "Nidoran-F",
		  gender: "F",
        forme: "Alola",
        formeLetter: "A",
        types: ["Grass"],
        baseStats: { FROM HERE
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },
	     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    },     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
    }, */
    };
