'use strict';

exports.BattleMovedex = {
	"scorchingwater": {
		    accuracy: 100,
		    basePower: 70,
	      category: "Special",
		    desc: "Has a 30% chance to burn the target. This move's type effectiveness against Ice is changed to be super effective no matter what this move's type is.",
		    shortDesc: "30% chance to burn the target. Thaws user. Super effective on Ice.",
		    id: "scorchingwater",
		    name: "Scorching Water",
		    pp: 15,
		    priority: 0,
		    flags: {protect: 1, mirror: 1, defrost: 1},
		    secondary: {
      			chance: 30,
  		    	status: 'brn',
  		  },
  		  target: "normal",
  		  type: "Water",
  		  zMovePower: 140,
  		  contestType: "Tough",
	},
	"boilingpoint": {
	  	  accuracy: 100,
  		  basePower: 80,
  		  basePowerCallback: function (pokemon, target, move) {
  			    if (target.status === 'brn') return move.basePower * 2;
  			    return move.basePower;
  		  },
  		  category: "Special",
  		  desc: "Power doubles if the target is burned.",
  		  shortDesc: "Power doubles if the target is burned.",
  		  id: "boilingpoint",
  		  name: "Boiling Point",
  		  pp: 10,
  		  priority: 0,
  		  flags: {protect: 1, mirror: 1},
  		  secondary: false,
  		  target: "normal",
  		  type: "Water",
  		  zMovePower: 160,
  		  contestType: "Tough",
	},
	"shurikenjet": {
	  	  accuracy: 100,
  		  basePower: 40,
  		  category: "Physical",
  		  desc: "Hits two to five times. Has a 1/3 chance to hit two or three times, and a 1/6 chance to hit four or five times. If one of the hits breaks the target's substitute, it will take damage for the remaining hits. If the user has the Ability Skill Link, this move will always hit five times.",
  		  shortDesc: "Hits 2-5 times in one turn.",
  		  id: "shurikenjet",
  		  name: "Shuriken Jet",
  		  pp: 10,
  		  priority: 1,
  		  flags: {protect: 1, mirror: 1},
  		  multihit: [2, 5],
  		  secondary: false,
  		  target: "normal",
  		  type: "Water",
  		  zMovePower: 190,
  		  contestType: "Cool",
	},
	"thermalslam": {
        accuracy: 100,
        basePower: 75,
        category: "Physical",
        desc: "Has a 20% chance to burn the target.",
        shortDesc: "20% chance to burn the target.",
        id: "thermalslam",
        name: "Thermal Slam",
        pp: 15,
        priority: 0,
        flags: {protect: 1, mirror: 1, defrost: 1},
        secondary: {
            chance: 30,
            status: 'brn',
        },
        target: "normal",
        type: "Water",
        zMovePower: 140,
        contestType: "Tough",
	},
	"toyshurikens": {
        accuracy: 85,
        basePower: 10,
        category: "Physical",
        desc: "Hits two to five times, with each hit having a 30% chance to lower the target's Attack by 1 stage. Has a 1/3 chance to hit two or three times, and a 1/6 chance to hit four or five times. If one of the hits breaks the target's substitute, it will take damage for the remaining hits. If the user has the Ability Skill Link, this move will always hit five times.",
        shortDesc: "Hits 2-5 times in one turn. Each hit has 30% chance to lower Attack.",
        id: "toyshurikens",
        name: "Toy Shurikens",
        pp: 15,
        priority: 0,
        flags: {protect: 1, mirror: 1},
        multihit: [2, 5],
        secondary: {
            chance: 30,
            boosts: {
                atk: -1,
            },
        },
        target: "normal",
        type: "Water",
        zMovePower: 100,
        contestType: "Cute",
	},
	"schemingsteam": {
        accuracy: 100,
        basePower: 40,
        category: "Physical",
        desc: "Prevents the target from using non-damaging moves for the duration of the turn. Pokemon with the Ability Oblivious or protected by the Ability Aroma Veil are immune to the secondary effect.",
        shortDesc: "Usually goes first. 100% Taunt chance.",
        id: "schemingsteam",
        name: "Scheming Steam",
        pp: 10,
        priority: 1,
        flags: {protect: 1, mirror: 1},
        secondary: {
            chance: 100,
            effect: {
                duration: 1,
                onStart: function (target) {
                    this.add('-start', target, 'move: Taunt');
                },
                onResidualOrder: 12,
                onEnd: function (target) {
                    this.add('-end', target, 'move: Taunt');
                },
                onDisableMove: function (pokemon) {
                    let moves = pokemon.moveset;
                    for (let i = 0; i < moves.length; i++) {
                        if (this.getMove(moves[i].move).category === 'Status') {
                            pokemon.disableMove(moves[i].id);
                        }
                    }
                },
                onBeforeMovePriority: 5,
                onBeforeMove: function (attacker, defender, move) {
                    if (!move.isZ && move.category === 'Status') {
                        this.add('cant', attacker, 'move: Taunt', move);
                        return false;
                    }
                },
            },
        },
        target: "normal",
        type: "Water",
        zMovePower: 100,
        contestType: "Clever",
	},
	"bodyblast": {
        accuracy: 90,
        basePower: 100,
        category: "Special",
        desc: "Has a 30% chance to paralyze the target.",
        shortDesc: "30% chance to paralyze the target.",
        id: "bodyblast",
        name: "Body Blast",
        pp: 10,
        priority: 0,
        flags: {protect: 1, mirror: 1},
        secondary: {
            chance: 30,
            status: 'par',
        },
        target: "normal",
        type: "Normal",
        zMovePower: 180,
        contestType: "Tough",
	},
	"possession": {
        accuracy: 75,
        basePower: 100,
        category: "Physical",
        desc: "Has a 30% chance to paralyze the target.",
        shortDesc: "30% chance to paralyze the target.",
        id: "possession",
        name: "Possession",
        pp: 15,
        priority: 0,
        flags: {protect: 1, mirror: 1},
        secondary: {
            chance: 30,
            status: 'par',
        },
        target: "normal",
        type: "Ghost",
        zMovePower: 180,
        contestType: "Cool",
	},
	"rockfall": {
        accuracy: 90,
        basePower: 55,
        category: "Physical",
        desc: "Hits two times, with each hit having a 50% chance to lower the target's Speed by one stage. If the first hit breaks the target's substitute, it will take damage for the second hit.",
        shortDesc: "Hits 2 times. Each hit has 50% chance to lower Speed.",
        id: "rockfall",
        name: "Rockfall",
        pp: 15,
        priority: 0,
        flags: {protect: 1, mirror: 1},
        multihit: [2, 2],
        secondary: {
            chance: 50,
            boosts: {
                spe: -1,
            },
        },
        target: "normal",
        type: "Rock",
        zMovePower: 100,
        contestType: "Clever",
	},
	"freneticcrush": {
        accuracy: 100,
        basePower: 60,
        category: "Physical",
        desc: "Has a 100% chance to raise the user's Speed by 1 stage. Has a 50% chance to raise the user's Attack by 1 stage.",
        shortDesc: "100% chance to raise the user's Speed by 1. 50% chance to raise the user's Attack by 1.",
        id: "freneticcrush",
        name: "Frenetic Crush",
        pp: 15,
        priority: 0,
        flags: {protect: 1, mirror: 1},
        secondaries: [
            {
                chance: 100,
                boosts: {
                    spe: 1,
                },
            }, {
                chance: 50,
                boosts: {
                    atk: 1,
                },
            },
        ],
        target: "normal",
        type: "Rock",
        zMovePower: 120,
        contestType: "Cool",
	},
	"abscond": {
        accuracy: true,
        basePower: 70,
        category: "Physical",
        desc: "If this move is successful and the user has not fainted, the user switches out even if it is trapped and is replaced immediately by a selected party member. The user does not switch out if there are no unfainted party members, or if the target switched out using an Eject Button.",
        shortDesc: "User switches out after damaging the target.",
        id: "abscond",
        name: "Abscond",
        pp: 20,
        priority: 0,
        flags: {protect: 1, mirror: 1},
        selfSwitch: true,
        secondary: false,
        target: "normal",
        type: "Dark",
        zMovePower: 140,
        contestType: "Clever",
	},
	"septicshock": {
        accuracy: 100,
        basePower: 70,
        category: "Physical",
        desc: "Has a 20% chance to either paralyze, freeze, or confuse the target.",
        shortDesc: "20% chance to paralyze or freeze or confuse the target.",
        id: "septicshock",
        name: "Septic Shock",
        pp: 20,
        priority: 0,
        flags: {protect: 1, mirror: 1},
        secondary: {
            chance: 20,
            onHit: function (target, source) {
                let result = this.random(3);
                if (result === 0) {
                    target.trySetStatus('par', source);
                } else if (result === 1) {
                    target.trySetStatus('frz', source);
                } else {
                    target.addVolatile('confusion');
                }
            }
        },
        target: "normal",
        type: "Water",
        zMovePower: 140,
        contestType: "Beautiful",
	},
	"riptide": {
        accuracy: 100,
        basePower: 90,
        category: "Physical",
        desc: "Has a 100% chance to lower the target's Speed by 1 stage.",
        shortDesc: "100% chance to lower adjacent Pkmn Speed by 1.",
        id: "riptide",
        name: "Riptide",
        pp: 15,
        priority: 0,
        flags: {protect: 1, mirror: 1, nonsky: 1},
        secondary: {
            chance: 100,
            boosts: {
                spe: -1,
            },
        },
        target: "allAdjacent",
        type: "Water",
        zMovePower: 175,
        contestType: "Tough",
	},
	"hydrothermalcrash": {
        accuracy: 95,
        basePower: 120,
        category: "Physical",
        desc: "Has a 50% chance to burn the target. The target thaws out if it is frozen.",
        shortDesc: "50% chance to burn the target. Thaws user.",
        id: "hydrothermalcrash",
        name: "Hydrothermal Crash",
        pp: 10,
        priority: 0,
        flags: {contact: 1, protect: 1, mirror: 1, defrost: 1},
        thawsTarget: true,
        secondary: {
            chance: 50,
            status: 'brn',
        },
        target: "normal",
        type: "Water",
        zMovePower: 190,
        contestType: "Tough",
	},
	"whaleslap": {
        accuracy: 90,
        basePower: 45,
        category: "Physical",
        desc: "Hits two to five times. Has a 1/3 chance to hit two or three times, and a 1/6 chance to hit four or five times. If one of the hits breaks the target's substitute, it will take damage for the remaining hits. If the user has the Ability Skill Link, this move will always hit five times.",
        shortDesc: "Hits 2-5 times in one turn.",
        pp: 5,
        priority: 0,
        flags: {contact: 1, protect: 1, mirror: 1},
        multihit: [2, 5],
        secondary: false,
        target: "normal",
        type: "Water",
        zMovePower: 195,
        contestType: "Cute",
	},
	"dragonsfire": {
        accuracy: 100,
        basePower: 75,
        category: "Physical",
        desc: "Has a 20% chance to burn the target. The target thaws out if it is frozen.",
        shortDesc: "30% chance to burn the target. Thaws target.",
        id: "dragonsfire",
        name: "Dragon's Fire",
        pp: 15,
        priority: 0,
        flags: {contact: 1, protect: 1, mirror: 1, defrost: 1},
        thawsTarget: true,
        secondary: {
            chance: 20,
            status: 'brn',
        },
        target: "normal",
        type: "Dragon",
        zMovePower: 140,
        contestType: "Cool",
	},
	"solareclipse": {
        accuracy: 90,
        basePower: 130,
        category: "Special",
        desc: "Lowers the user's Special Attack by 2 stages.",
        shortDesc: "Lowers the user's Sp. Atk by 2.",
        id: "solareclipse",
        name: "Solar Eclipse",
        pp: 5,
        priority: 0,
        flags: {protect: 1, mirror: 1},
        self: {
            boosts: {
                spa: -2,
            },
        },
        secondary: false,
        target: "normal",
        type: "Dark",
        zMovePower: 195,
        contestType: "Beautiful",
	},
	"quickdraw": {
        accuracy: 100,
        basePower: 80,
        category: "Physical",
        desc: "Higher priority if the user has no held item. Fails if the target did not select a physical attack, special attack, or Me First for use this turn, or if the target moves before the user.",
        shortDesc: "Usually goes first, especially if the user has no held item. Fails if target is not attacking.",
        id: "quickdraw",
        name: "Quick Draw",
        pp: 5,
        priority: 1,
        priorityCallback: function (pokemon, target, move) {
            if (!pokemon.item) {
                this.debug("Priority increased for no item");
                return move.priority + 1;
            }
            return move.priority;
        },
        flags: {contact: 1, protect: 1, mirror: 1},
        onTry: function (source, target) {
			      let decision = this.willMove(target);
			      if (!decision || decision.choice !== 'move' || (decision.move.category === 'Status' && decision.move.id !== 'mefirst') || target.volatiles.mustrecharge) {
				        this.attrLastMove('[still]');
  				      this.add('-fail', source);
	  			      return null;
			      }
		    },
        secondary: false,
        target: "normal",
        type: "Dark",
        zMovePower: 160,
        contestType: "Cool",
	},
	"deathknell": {
        accuracy: 95,
        basePower: 20,
        category: "Physical",
        desc: "Prevents the target from switching for four or five turns; seven turns if the user is holding Grip Claw. Causes the target's last move to lose 4 PP, if applicable, at the end of each turn during effect. The target can still switch out if it is holding Shed Shell or uses Baton Pass, Parting Shot, U-turn, or Volt Switch. The effect ends if either the user or the target leaves the field, or if the target uses Rapid Spin or Substitute. This effect is not stackable or reset by using this or another partial-trapping move.",
        shortDesc: "Traps the target and lowers its PP for 4-5 turns.",
        id: "deathknell",
        name: "Death Knell",
        pp: 10,
        priority: 0,
        flags: {protect: 1, mirror: 1},
        volatileStatus: 'deathknell',
        secondary: false,
        target: "normal",
        type: "Ghost",
        zMovePower: 100,
        contestType: "Tough",
	},
	"geyser": {
        accuracy: 95,
        basePower: 90,
        category: "Special",
        desc: "If this move is successful and the user has not fainted, the user switches out even if it is trapped and is replaced immediately by a selected party member. The user does not switch out if there are no unfainted party members, or if the target switched out using an Eject Button.",
        shortDesc: "User switches out after damaging the target.",
        id: "geyser",
        name: "Geyser",
        pp: 15,
        priority: 0,
		    flags: {protect: 1, mirror: 1},
		    selfSwitch: true,
		    secondary: false,
		    target: "normal",
		    type: "Water",
		    zMovePower: 175,
		    contestType: "Beautiful",
	},
	"leechingsting": {
        accuracy: 100,
        basePower: 80,
        category: "Physical",
        desc: "The user recovers 3/4 the HP lost by the target, rounded half up. If Big Root is held by the user, the HP recovered is 1.3x normal, rounded half down.",
        shortDesc: "User recovers 75% of the damage dealt.",
        id: "leechingsting",
        name: "Leeching Sting",
        pp: 10,
        priority: 0,
        flags: {protect: 1, mirror: 1, heal: 1},
        drain: [3, 4],
        secondary: false,
        target: "normal",
        type: "Bug",
        zMovePower: 160,
        contestType: "Tough",
	},
	"blazeofglory": {
        accuracy: 100,
        basePower: 80,
        category: "Physical",
        desc: "Has a 100% chance to burn the target. Fails if the target did not select a physical attack, special attack, or Me First for use this turn, or if the target moves before the user.",
        shortDesc: "Usually goes first. 100% chance to burn the target. Fails if target is not attacking.",
        pp: 5,
        priority: 1,
		    flags: {contact: 1, protect: 1, mirror: 1},
		    onTry: function (source, target) {
			      let decision = this.willMove(target);
			      if (!decision || decision.choice !== 'move' || (decision.move.category === 'Status' && decision.move.id !== 'mefirst') || target.volatiles.mustrecharge) {
				        this.attrLastMove('[still]');
				        this.add('-fail', source);
				        return null;
			      }
		    },
		    secondary: {
            chance: 100,
            status: 'brn',
        },
		    target: "normal",
        type: "Fire",
        zMovePower: 160,
        contestType: "Beautiful",
	},
	"beakblade": {
        accuracy: 90,
        basePower: 70,
        category: "Physical",
        defensiveCategory: "Special",
        desc: "This move is always a critical hit unless the target is under the effect of Lucky Chant or has the Abilities Battle Armor or Shell Armor. Deals damage to the target based on its Special Defense instead of Defense.",
        shortDesc: "Always results in a critical hit. Damages target based on Sp. Def, not Defense.",
        pp: 15,
        priority: 0,
        flags: {protect: 1, mirror: 1},
        secondary: false,
        target: "normal",
        type: "Flying",
        zMovePower: 140,
        contestType: "Tough",
	},
	"cactussting": {
        // How/where does the 1/8 HP drain come into effect?
        accuracy: 100,
        basePower: 55,
        category: "Physical",
        desc: "Has a 100% chance to lower the target's Speed by 1 stage. Steals 1/8 of the target's maximum HP, rounded down. If Big Root is held by the recipient, the HP recovered is 1.3x normal, rounded half down.",
        shortDesc: "100% chance to lower target's Speed by 1. 1/8 of target's HP is restored to user.",
        pp: 15,
        priority: 0,
        flags: {protect: 1, mirror: 1},
        secondary: {
            chance: 100,
            boosts: {
                spe: -1,
            },
        },
        target: "normal",
        type: "Grass",
        zMovePower: 100,
        contestType: "Tough",
	  },
};
