'use strict';

exports.BattleLearnsets = {
tapulele: {learnset: {
		aromatherapy: ["7L1"],
		aromaticmist: ["7L1"],
		astonish: ["7L1"],
		calmmind: ["7M"],
		chargebeam: ["7M"],
		confide: ["7M"],
		confusion: ["7L1"],
		dazzlinggleam: ["7M"],
		doubleteam: ["7M"],
		drainingkiss: ["7L1"],
		echoedvoice: ["7M"],
		energyball: ["7M"],
		extrasensory: ["7L48", "7S0"],
		facade: ["7M"],
		flatter: ["7L53", "7S0"],
		fling: ["7M"],
		focusblast: ["7M"],
		frustration: ["7M"],
		gigaimpact: ["7M"],
		grassknot: ["7M"],
		hiddenpower: ["7M"],
		hyperbeam: ["7M"],
		lightscreen: ["7M"],
		meanlook: ["7L1"],
		moonblast: ["7L58", "7S0"],
		naturepower: ["7M"],
		protect: ["7M"],
		psybeam: ["7L14"],
		psychic: ["7M"],
		psychicterrain: ["7L1"],
		psychup: ["7M"],
		psyshock: ["7M", "7L32"],
		psywave: ["7L8"],
		reflect: ["7M"],
		return: ["7M"],
		round: ["7M"],
		safeguard: ["7M"],
		shadowball: ["7M"],
		skillswap: ["7L26"],
		sleeptalk: ["7M"],
		substitute: ["7M"],
		sunnyday: ["7M"],
		swagger: ["7M"],
		sweetscent: ["7L20"],
		taunt: ["7M"],
		thief: ["7M"],
		thunder: ["7M"],
		thunderbolt: ["7M"],
		tickle: ["7L38"],
		torment: ["7M"],
		toxic: ["7M"],
		withdraw: ["7L1"],
	}},
  tapubulu: {learnset: {
		brickbreak: ["7M"],
		brutalswing: ["7M"],
		bulkup: ["7M"],
		calmmind: ["7M"],
		confide: ["7M"],
		dazzlinggleam: ["7M"],
		disable: ["7L1"],
		echoedvoice: ["7M"],
		energyball: ["7M"],
		facade: ["7M"],
		falseswipe: ["7M"],
		fling: ["7M"],
		focusblast: ["7M"],
		frustration: ["7M"],
		gigadrain: ["7L14"],
		gigaimpact: ["7M"],
		grassknot: ["7M"],
		grassyterrain: ["7L1"],
		hiddenpower: ["7M"],
		hornattack: ["7L8"],
		hornleech: ["7L32"],
		hyperbeam: ["7M"],
		leafage: ["7L1"],
		leechseed: ["7L26"],
		lightscreen: ["7M"],
		meanlook: ["7L1"],
		megahorn: ["7L53", "7S0"],
		naturepower: ["7M"],
		naturesmadness: ["7L43", "7S0"],
		payback: ["7M"],
		protect: ["7M"],
		psychup: ["7M"],
		reflect: ["7M"],
		return: ["7M"],
		roar: ["7M"],
		rockslide: ["7M"],
		rocktomb: ["7M"],
		rototiller: ["7L38"],
		round: ["7M"],
		safeguard: ["7M"],
		scaryface: ["7L20"],
		skullbash: ["7L58", "7S0"],
		sleeptalk: ["7M"],
		smartstrike: ["7M"],
		snarl: ["7M"],
		solarbeam: ["7M"],
		stoneedge: ["7M"],
		substitute: ["7M"],
		sunnyday: ["7M"],
		swagger: ["7M"],
		swordsdance: ["7M"],
		taunt: ["7M"],
		torment: ["7M"],
		toxic: ["7M"],
		whirlwind: ["7L1"],
		withdraw: ["7L1"],
		woodhammer: ["7L1"],
		workup: ["7M"],
		zenheadbutt: ["7L48", "7S0"],
	}},
  tapufini: {learnset: {
		blizzard: ["7M"],
		brine: ["7L32"],
		calmmind: ["7M"],
		confide: ["7M"],
		dazzlinggleam: ["7M"],
		defog: ["7L38"],
		doubleteam: ["7M"],
		echoedvoice: ["7M"],
		facade: ["7M"],
		fling: ["7M"],
		frustration: ["7M"],
		gigaimpact: ["7M"],
		grassknot: ["7M"],
		healpulse: ["7L1"],
		hiddenpower: ["7M"],
		hydropump: ["7L58", "7S0"],
		hyperbeam: ["7M"],
		icebeam: ["7M"],
		lightscreen: ["7M"],
		meanlook: ["7L1"],
		mist: ["7L1"],
		mistyterrain: ["7L1"],
		moonblast: ["7L1"],
		muddywater: ["7L48", "7S0"],
		naturepower: ["7M"],
		naturesmadness: ["7L43", "7S0"],
		protect: ["7M"],
		psychup: ["7M"],
		raindance: ["7M"],
		reflect: ["7M"],
		refresh: ["7L26"],
		return: ["7M"],
		round: ["7M"],
		safeguard: ["7M"],
		scald: ["7M"],
		shadowball: ["7M"],
		sleeptalk: ["7M"],
		smartstrike: ["7M"],
		soak: ["7L20"],
		substitute: ["7M"],
		surf: ["7M"],
		swagger: ["7M"],
		torment: ["7M"],
		toxic: ["7M"],
		waterfall: ["7M"],
		watergun: ["7L1"],
		waterpulse: ["7L8"],
		whirlpool: ["7L14"],
		withdraw: ["7L1"],
	}},
  magearna: {learnset: {
		aurorabeam: ["7L17"],
		brickbreak: ["7M"],
		calmmind: ["7M"],
		chargebeam: ["7M"],
		confide: ["7M"],
		craftyshield: ["7L1"],
		dazzlinggleam: ["7M"],
		defensecurl: ["7L1"],
		doubleteam: ["7M"],
		echoedvoice: ["7M"],
		embargo: ["7M"],
		energyball: ["7M"],
		explosion: ["7M"],
		falseswipe: ["7M"],
		flashcannon: ["7M", "7L41", "7S0"],
		fleurcannon: ["7L49", "7S0"],
		frustration: ["7M"],
		gearup: ["7L1"],
		gigaimpact: ["7M"],
		grassknot: ["7M"],
		gyroball: ["7M"],
		heartswap: ["7L89"],
		helpinghand: ["7L1", "7S0"],
		hiddenpower: ["7M"],
		hyperbeam: ["7M"],
		irondefense: ["7L57"],
		ironhead: ["7L1"],
		lightscreen: ["7M"],
		luckychant: ["7L9", "7S0"],
		mindreader: ["7L33"],
		mirrorshot: ["7L25"],
		painsplit: ["7L65"],
		protect: ["7M"],
		psybeam: ["7L1"],
		reflect: ["7M"],
		return: ["7M"],
		round: ["7M"],
		shadowball: ["7M"],
		shiftgear: ["7L1"],
		solarbeam: ["7M"],
		sonicboom: ["7L1"],
		substitute: ["7M"],
		swagger: ["7M"],
		synchronoise: ["7L73"],
		thunderbolt: ["7M"],
		thunderwave: ["7M"],
		trumpcard: ["7L97"],
    playrough: ["7M"],
    rollout: ["7M"],
    toxic: ["7M"],
    rest: ["7M"],
    sleeptalk: ["7M"],
	}},
  magearnaoriginal: {learnset: {
		aurasphere: ["7L81"],
		aurorabeam: ["7L17"],
		brickbreak: ["7M"],
		calmmind: ["7M"],
		chargebeam: ["7M"],
		confide: ["7M"],
		craftyshield: ["7L1"],
		dazzlinggleam: ["7M"],
		defensecurl: ["7L1"],
		doubleteam: ["7M"],
		echoedvoice: ["7M"],
		embargo: ["7M"],
		energyball: ["7M"],
		explosion: ["7M"],
		falseswipe: ["7M"],
		flashcannon: ["7M", "7L41", "7S0"],
		fleurcannon: ["7L49", "7S0"],
		focusblast: ["7M"],
		frustration: ["7M"],
		gearup: ["7L1"],
		gigaimpact: ["7M"],
		grassknot: ["7M"],
		gyroball: ["7M"],
		heartswap: ["7L89"],
		helpinghand: ["7L1", "7S0"],
		hiddenpower: ["7M"],
		hyperbeam: ["7M"],
		icebeam: ["7M"],
		irondefense: ["7L57"],
		ironhead: ["7L1"],
		lightscreen: ["7M"],
		luckychant: ["7L9", "7S0"],
		mindreader: ["7L33"],
		mirrorshot: ["7L25"],
		painsplit: ["7L65"],
		protect: ["7M"],
		psybeam: ["7L1"],
		reflect: ["7M"],
		return: ["7M"],
		round: ["7M"],
		shadowball: ["7M"],
		shiftgear: ["7L1"],
		solarbeam: ["7M"],
		sonicboom: ["7L1"],
		substitute: ["7M"],
		swagger: ["7M"],
		synchronoise: ["7L73"],
		thunderbolt: ["7M"],
		thunderwave: ["7M"],
		trickroom: ["7M"],
		trumpcard: ["7L97"],
		voltswitch: ["7M"],
	}},
};
