'use strict';

 exports.BattlePokedex = {
tapulele: {
		num: 786,
		species: "Tapu Lele",
		types: ["Psychic", "Fairy"],
		gender: "N",
		baseStats: {hp: 70, atk: 85, def: 75, spa: 100, spd: 115, spe: 95},
		abilities: {0: "Competitive", H: "Telepathy"},
		heightm: 1.2,
		weightkg: 18.6,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
  tapubulu: {
		num: 787,
		species: "Tapu Bulu",
		types: ["Grass", "Fairy"],
		gender: "N",
		baseStats: {hp: 70, atk: 125, def: 95, spa: 85, spd: 85, spe: 70},
		abilities: {0: "Sap Sipper", H: "Telepathy"},
		heightm: 1.9,
		weightkg: 45.5,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
  tapufini: {
		num: 788,
		species: "Tapu Fini",
		types: ["Water", "Fairy"],
		gender: "N",
		baseStats: {hp: 60, atk: 75, def: 100, spa: 85, spd: 115, spe: 85},
		abilities: {0: "Water Veil", H: "Telepathy"},
		heightm: 1.3,
		weightkg: 21.2,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
  magearna: {
		num: 801,
		species: "Magearna",
		types: ["Fairy"],
		gender: "N",
		baseStats: {hp: 80, atk: 105, def: 95, spa: 105, spd: 95, spe: 75},
		abilities: {0: "Steelworker"},
		heightm: 1,
		weightkg: 80.5,
		color: "Gray",
		eggGroups: ["Undiscovered"],
		otherFormes: ["magearnaoriginal"],
	},
  magearnaoriginal: {
		num: 801,
		species: "Magearna-Original",
		baseSpecies: "Magearna",
		forme: "Original",
		formeLetter: "O",
		types: ["Steel", "Fairy"],
		gender: "N",
		baseStats: {hp: 80, atk: 95, def: 115, spa: 130, spd: 115, spe: 65},
		abilities: {0: "Soul-Heart"},
		heightm: 1,
		weightkg: 80.5,
		color: "Red",
		eggGroups: ["Undiscovered"],
		spritenum: 804 + 152,
	},
  };
