'use strict';

exports.BattlePokedex = {
pansageeternal: {
        num: 511,
        species: "Pansage-Eternal",
        baseSpecies: "Pansage",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Grass","Fighting"],
        baseStats: {hp: 60, atk: 103, def: 59, spa: 103, spd: 59, spe: 113},
        abilities: {0: "Gluttony", H: "Overgrow"},
        },
        panseareternal: {
        num: 513,
        species: "Pansear-Eternal",
        baseSpecies: "Pansear",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Fire","Rock"],
        baseStats: {hp: 71, atk: 53, def: 78, spa: 113, spd: 78, spe: 104},
        abilities: {0: "Gluttony", H: "Blaze"},
        },
        panpoureternal: {
        num: 515,
        species: "Panpour-Eternal",
        baseSpecies: "Panpour",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Water","Ice"],
        baseStats: {hp: 80, atk: 103, def: 48, spa: 103, spd: 48, spe: 110},
        abilities: {0: "Gluttony", H: "Torrent"},
        },
        pikachueternal: {
        num: 25,
        species: "Pikachu-Eternal",
        baseSpecies: "Pikachu",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Electric"],
        baseStats: {hp: 65, atk: 65, def: 90, spa: 60, spd: 100, spe: 114},
        abilities: {0: "Static", H: "Lightningrod"},
        },
        eeveeeternal: {
        num: 133,
        species: "Eevee-Eternal",
        baseSpecies: "Eevee",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Normal"],
        baseStats: {hp: 70, atk: 92, def: 70, spa: 92, spd: 80, spe: 110},
        abilities: {0: "Run Away", 1: "Adaptability", H: "Anticipation"},
        },
        murkroweternal: {
        num: 198,
        species: "Murkrow-Eternal",
        baseSpecies: "Murkrow",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Dark","Flying"],
        baseStats: {hp: 73, atk: 107, def: 57, spa: 107, spd: 57, spe: 103},
        abilities: {0: "Insomnia", 1: "Super Luck", H: "Prankster"},
        },
        misdreavuseternal: {
        num: 200,
        species: "Misdreavus-Eternal",
        baseSpecies: "Misdreavus",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Ghost","Fairy"],
        baseStats: {hp: 61, atk: 61, def: 61, spa: 123, spd: 61, spe: 123},
        abilities: {0: "Levitate"},
        },
        lampenteternal: {
        num: 608,
        species: "Lampent-Eternal",
        baseSpecies: "Murkrow",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Ghost","Fire"],
        baseStats: {hp: 75, atk: 50, def: 70, spa: 119, spd: 70, spe: 105},
        abilities: {0: "Flash Fire", 1: "Flame Body", H: "Infiltrator"},
        },
        doubladeeternal: {
        num: 680,
        species: "Doublade-Eternal",
        baseSpecies: "Doublade",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Steel","Ghost"],
        baseStats: {hp: 59, atk: 160, def: 160, spa: 45, spd: 59, spe: 36},
        abilities: {0: "No Guard"},
        },
        kabadraeternal: {
        num: 64,
        species: "Kadabra-Eternal",
        baseSpecies: "Kadabra",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Psyhic","Ice"],
        baseStats: {hp: 60, atk: 35, def: 65, spa: 144, spd: 80, spe: 115},
        abilities: {0: "Synchronize", 1: "Inner Focus", H: "Magic Guard"},
        },
        machokeeternal: {
        num: 67,
        species: "Machoke-Eternal",
        baseSpecies: "Machoke",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Fighting","Steel"],
        baseStats: {hp: 100, atk: 133, def: 88, spa: 50, spd: 60, spe: 73},
        abilities: {0: "Guts", 1: "No Guard", H: "Steadfast"},
        },
        gravelereternal: {
        num: 75,
        species: "Graveler-Eternal",
        baseSpecies: "Graveler",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Rock","Ground"],
        baseStats: {hp: 55, atk: 129, def: 115, spa: 45, spd: 45, spe: 105},
        abilities: {0: "Rock Head", 1: "Sturdy", H: "Sand Veil"},
        },
        hauntereternal: {
        num: 93,
        species: "Haunter-Eternal",
        baseSpecies: "Haunter",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Ghost","Dark"],
        baseStats: {hp: 55, atk: 50, def: 45, spa: 133, spd: 88, spe: 133},
        abilities: {0: "Levitate"},
        },
        magnetoneternal: {
        num: 82,
        species: "Magneton-Eternal",
        baseSpecies: "Magneton",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Electric","Steel"],
        baseStats: {hp: 60, atk: 60, def: 95, spa: 145, spd: 80, spe: 94},
        abilities: {0: "Magnet Pull", 1:"Sturdy", H: "Analytic"},
        },
        nosepasseternal: {
        num: 299,
        species: "Nosepass-Eternal",
        baseSpecies: "Nosepass",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Rock","Psychic"],
        baseStats: {hp: 70, atk: 65, def: 154, spa: 95, spd: 120, spe: 30},
        abilities: {0: "Sturdy", 1:"Magnet Pull", H: "Sand Force"},
        },
        charjabugeternal: {
        num: 737,
        species: "Charjabug-Eternal",
        baseSpecies: "Charjabug",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Bug","Electric"],
        baseStats: {hp: 77, atk: 131, def: 117, spa: 57, spd: 77, spe: 40},
        abilities: {0: "Battery"},
        },
        magikarpeternal: {
        num: 129,
        species: "Magikarp-Eternal",
        baseSpecies: "Magikarp",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Water","Flying"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 90, spd: 80, spe: 109},
        abilities: {0: "Swift Swim", H: "Rattled"},
        },
        feebaseternal: {
        num: 349,
        species: "Feebas-Eternal",
        baseSpecies: "Feebas",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Water"],
        baseStats: {hp: 118, atk: 18, def: 98, spa: 68, spd: 118, spe: 119},
        abilities: {0: "Swift Swim", 1: "Oblivious", H: "Adaptability"},
        },
        wimpodeternal: {
        num: 767,
        species: "Wimpod-Eternal",
        baseSpecies: "Wimpod",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Bug","Water"],
        baseStats: {hp: 125, atk: 100, def: 74, spa: 35, spd: 80, spe: 115},
        abilities: {0: "Wimp Out"},
        },
        dartrixeternal: {
        num: 723,
        species: "Dartrix-Eternal",
        baseSpecies: "Dartrix",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Grass","Rock"],
        baseStats: {hp: 76, atk: 78, def: 108, spa: 101, spd: 74, spe: 92},
        abilities: {0: "Overgrow", H: "Long Reach"},
        },
        torracateternal: {
        num: 726,
        species: "Torracat-Eternal",
        baseSpecies: "Torracat",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Fire","Dragon"],
        baseStats: {hp: 77, atk: 96, def: 66, spa: 104, spd: 67, spe: 119},
        abilities: {0: "Blaze", H: "Intimidate"},
        },
        brionneeternal: {
        num: 729,
        species: "Brionne-Eternal",
        baseSpecies: "Brionne",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Water","Psychic"],
        baseStats: {hp: 60, atk: 69, def: 108, spa: 131, spd: 111, spe: 50},
        abilities: {0: "Torrent", H: "Liquid Voice"},
        },
        onixeternal: {
        num: 95,
        species: "Onix-Eternal",
        baseSpecies: "Onix",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Rock","Dragon"],
        baseStats: {hp: 40, atk: 18, def: 174, spa: 92, spd: 69, spe: 116},
        abilities: {0: "Rock Head", 1: "Sturdy", H: "Weak Armor"},
        },
        chanseyeternal: {
        num: 113,
        species: "Chansey-Eternal",
        baseSpecies: "Chansey",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Normal","Fairy"],
        baseStats: {hp: 250, atk: 5, def: 64, spa: 35, spd: 135, spe: 50},
        abilities: {0: "Natural Cure", 1: "Serene Grace", H: "Healer"},
        },
        cranidoseternal: {
        num: 408,
        species: "Cranidos-Eternal",
        baseSpecies: "Cranidos",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Rock","Dark"],
        baseStats: {hp: 107, atk: 155, def: 59, spa: 19, spd: 51, spe: 103},
        abilities: {0: "Mold Breaker", H: "Sheer Force"},
        },
        sneaseleternal: {
        num: 215,
        species: "Sneasel-Eternal",
        baseSpecies: "Sneasel",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Ghost","Ice"],
        baseStats: {hp: 60, atk: 44, def: 64, spa: 124, spd: 93, spe: 124},
        abilities: {0: "Inner Focus", 1: "Keen Eye", H: "Pickpocket"},
        },
        duosioneternal: {
        num: 578,
        species: "Duosion-Eternal",
        baseSpecies: "Duosion",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Psychic","Grass"],
        baseStats: {hp: 82, atk: 42, def: 102, spa: 129, spd: 92, spe: 42},
        abilities: {0: "Overcoat", 1: "Magic Guard", H: "Regenerator"},
        },
        cosmoemeternal: {
        num: 790,
        species: "Cosmoem-Eternal",
        baseSpecies: "Cosmoem",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Psychic","Rock"],
        baseStats: {hp: 71, atk: 137, def: 151, spa: 137, spd: 181, spe: 2},
        abilities: {0: "Sturdy"},
        },
        tangelaeternal: {
        num: 114,
        species: "Tangela-Eternal",
        baseSpecies: "Tangela",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Grass","Dark"],
        baseStats: {hp: 121, atk: 100, def: 116, spa: 56, spd: 54, spe: 87},
        abilities: {0: "Chlorophyll", 1: "Leaf Guard", H: "Regenerator"},
        },
        yanmaeternal: {
        num: 193,
        species: "Yanma-Eternal",
        baseSpecies: "Yanma",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Bug","Dragon"],
        baseStats: {hp: 65, atk: 45, def: 101, spa: 101, spd: 96, spe: 106},
        abilities: {0: "Speed Boost", 1: "Coumpoundeyes", H: "Frisk"},
        },
        piloswineeternal: {
        num: 221,
        species: "Piloswine-Eternal",
        baseSpecies: "Piloswine",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Ground"],
        baseStats: {hp: 104, atk: 105, def: 95, spa: 65, spd: 105, spe: 55},
        abilities: {0: "Oblivious", 1: "Snow Cloak", H: "Thick Fat"},
        },
        dragonaireternal: {
        num: 148,
        species: "Dragonair-Eternal",
        baseSpecies: "Dragonair",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Dragon", "Normal"],
        baseStats: {hp: 91, atk: 114, def: 94, spa: 90, spd: 109, spe: 101},
        abilities: {0: "Shed Skin", H: "Marvel Scale"},
        },
        pupitareternal: {
        num: 247,
        species: "Pupitar-Eternal",
        baseSpecies: "Pupitar",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Rock", "Ground"],
        baseStats: {hp: 94, atk: 124, def: 120, spa: 65, spd: 105, spe: 91},
        abilities: {0: "Shed Skin"},
        },
        shelgoneternal: {
        num: 372,
        species: "Shelgon-Eternal",
        baseSpecies: "Shelgon",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Dragon", "Steel"],
        baseStats: {hp: 64, atk: 128, def: 160, spa: 95, spd: 125, spe: 27},
        abilities: {0: "Rock Head", H: "Overcoat"},
        },
        metangeternal: {
        num: 375,
        species: "Metang-Eternal",
        baseSpecies: "Metang",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Steel", "Ghost"],
        baseStats: {hp: 83, atk: 105, def: 134, spa: 85, spd: 123, spe: 69},
        abilities: {0: "Clear Body", H: "Light Metal"},
        },
        gabiteeternal: {
        num: 444,
        species: "Gabite-Eternal",
        baseSpecies: "Gabite",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Dragon", "Water"],
        baseStats: {hp: 90, atk: 150, def: 90, spa: 79, spd: 90, spe: 100},
        abilities: {0: "Sand Veil", H: "Rough Skin"},
        },
        zweilouseternal: {
        num: 634,
        species: "Zweilous-Eternal",
        baseSpecies: "Zweilous",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Dark", "Dragon"],
        baseStats: {hp: 81, atk: 105, def: 105, spa: 105, spd: 105, spe: 98},
        abilities: {0: "Hustle"},
        },
        sliggooeternal: {
        num: 705,
        species: "Sliggoo-Eternal",
        baseSpecies: "Sliggoo",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Dragon", "Electric"],
        baseStats: {hp: 110, atk: 89, def: 105, spa: 115, spd: 100, spe: 80},
        abilities: {0: "Sap Sipper", 1: "Hydration", H: "Gooey"},
        },
        hakamooeternal: {
        num: 783,
        species: "Hakamo-o-Eternal",
        baseSpecies: "Hakamo-o",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Dragon", "Fighting"],
        baseStats: {hp: 34, atk: 130, def: 95, spa: 130, spd: 85, spe: 125},
        abilities: {0: "Bulletproof", 1: "Soundproof", H: "Overcoat"},
        },
        rhydoneternal: {
        num: 112,
        species: "Rhydon-Eternal",
        baseSpecies: "Rhydon",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Rock", "Dragon"],
        baseStats: {hp: 95, atk: 88, def: 90, spa: 130, spd: 50, spe: 81},
        abilities: {0: "Lightning Rod", 1: "Rock Head", H: "Reckless"},
        },
        laironeternal: {
        num: 305,
        species: "Lairon-Eternal",
        baseSpecies: "Lairon",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Steel", "Water"],
        baseStats: {hp: 80, atk: 80, def: 115, spa: 80, spd: 145, spe: 29},
        abilities: {0: "Sturdy", 1: "Rock Head", H: "Heavy Metal"},
        },
        shieldoneternal: {
        num: 410,
        species: "Shieldon-Eternal",
        baseSpecies: "Shieldon",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Rock"],
        baseStats: {hp: 100, atk: 72, def: 118, spa: 42, spd: 108, spe: 54},
        abilities: {0: "Sturdy", H: "Soundproof"},
        },
        ivysaureternal: {
        num: 2,
        species: "Ivysaur-Eternal",
        baseSpecies: "Ivysaur",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Dark", "Poison"],
        baseStats: {hp: 100, atk: 70, def: 120, spa: 100, spd: 99, spe: 35},
        abilities: {0: "Overgrow", H: "Chlorophyll"},
        },
        charmeleoneternal: {
        num: 5,
        species: "Charmeleon-Eternal",
        baseSpecies: "Charmeleon",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Fire", "Water"],
        baseStats: {hp: 98, atk: 82, def: 98, spa: 80, spd: 108, spe: 80},
        abilities: {0: "Blaze", H: "Solar Power"},
        },
        wartortleeternal: {
        num: 5,
        species: "Wartortle-Eternal",
        baseSpecies: "Wartortle",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Water", "Grass"],
        baseStats: {hp: 59, atk: 123, def: 80, spa: 70, spd: 80, spe: 118},
        abilities: {0: "Torrent", H: "Rain Dish"},
        },
        digltteternal: {
        num: 5,
        species: "Diglett-Eternal",
        baseSpecies: "Diglett",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Ground"],
        baseStats: {hp: 32, atk: 99, def: 48, spa: 58, spd: 68, spe: 119},
        abilities: {0: "Sand Veil", 1: "Arena Trap", H: "Sand Force"},
        },
        wynauteternal: {
        num: 5,
        species: "Wynaut-Eternal",
        baseSpecies: "Wynaut",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Psychic"],
        baseStats: {hp: 49, atk: 23, def: 143, spa: 23, spd: 143, spe: 23},
        abilities: {0: "Shadow Tag", H: "Telepathy"},
        },
        gothoritaeternal: {
        num: 5,
        species: "Gothorita-Eternal",
        baseSpecies: "Gothorita",
        forme: "Eternal",
        formeLetter: "E",
        types: ["Psychic", "Fairy"],
        baseStats: {hp: 80, atk: 24, def: 85, spa: 130, spd: 70, spe: 100},
        abilities: {0: "Frisk", 1: "Competitive", H: "Shadow Tag"},
        },
        };
