'use strict';

exports.BattleLearnsets = {
primarina: {learnset: {
		acrobatics: ["7M"],
		aquajet: ["7L15"],
		attract: ["7M"],
		babydolleyes: ["7L11"],
		blizzard: ["7M"],
		bubblebeam: ["7L24"],
		captivate: ["7L49"],
		confide: ["7M"],
		dazzlinggleam: ["7M"],
		disarmingvoice: ["7L9", "7L1"],
		doubleslap: ["7L33"],
		doubleteam: ["7M"],
		echoedvoice: ["7M"],
		encore: ["7L19"],
		energyball: ["7M"],
		facade: ["7M"],
		frustration: ["7M"],
		gigaimpact: ["7M"],
		growl: ["7L4", "7L1"],
		hail: ["7M"],
		hiddenpower: ["7M"],
		hydrocannon: ["7T"],
		hydropump: ["7L55"],
		hypervoice: ["7L38"],
		icebeam: ["7M"],
		lightscreen: ["7M"],
		mistyterrain: ["7L60"],
		moonblast: ["7L44"],
		pound: ["7L1"],
		protect: ["7M"],
		psychic: ["7M"],
		psychup: ["7M"],
		raindance: ["7M"],
		reflect: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		round: ["7M"],
		scald: ["7M"],
		shadowball: ["7M"],
		sing: ["7L28"],
		sleeptalk: ["7M"],
		sparklingaria: ["7L1"],
		substitute: ["7M"],
		surf: ["7M"],
		swagger: ["7M"],
		toxic: ["7M"],
		waterfall: ["7M"],
		watergun: ["7L1"],
		waterpledge: ["7T"],
		workup: ["7M"],
    perishsong: ["7L1"],
    recover: ["7L1"],
    whrilpool: ["7L1"],
    signalbeam: ["7L1"],
    boomburst: ["7L1"],
	}},
  };
