'use strict';

 exports.BattlePokedex = {
decidueye: {
		num: 724,
		species: "Decidueye",
		types: ["Grass", "Ghost"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 88, atk: 112, def: 75, spa: 100, spd: 125, spe: 80},
		abilities: {0: "Overgrow", H: "Long Reach"},
		heightm: 1.6,
		weightkg: 36.6,
		color: "Brown",
		prevo: "dartrix",
		evoLevel: 34,
		eggGroups: ["Flying"],
	},
 primarina: {
		num: 730,
		species: "Primarina",
		types: ["Water", "Fairy"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 90, atk: 74, def: 94, spa: 126, spd: 126, spe: 70},
		abilities: {0: "Torrent", H: "Liquid Voice"},
		heightm: 1.8,
		weightkg: 44,
		color: "Blue",
		prevo: "brionne",
		evoLevel: 34,
		eggGroups: ["Water 1", "Field"],
	},
	 incineroar: {
		num: 727,
		species: "Incineroar",
		types: ["Fire", "Dark"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 95, atk: 125, def: 95, spa: 80, spd: 90, spe: 95},
		abilities: {0: "Blaze", H: "Intimidate"},
		heightm: 1.8,
		weightkg: 83,
		color: "Red",
		prevo: "torracat",
		evoLevel: 34,
		eggGroups: ["Field"],
	},
	 ninjask: {
		num: 291,
		species: "Ninjask",
		types: ["Bug", "Flying"],
		baseStats: {hp: 61, atk: 109, def: 45, spa: 50, spd: 50, spe: 175},
		abilities: {0: "Speed Boost", H: "Adaptability"},
		heightm: 0.8,
		weightkg: 12,
		color: "Yellow",
		prevo: "nincada",
		evoLevel: 20,
		eggGroups: ["Bug"],
	},
	 shedinja: {
		num: 292,
		species: "Shedinja",
		types: ["Bug", "Ghost"],
		gender: "N",
		baseStats: {hp: 1, atk: 100, def: 30, spa: 30, spd: 30, spe: 40},
		maxHP: 1,
		abilities: {0: "Wonder Guard", H: "Shed Skin"},
		heightm: 0.8,
		weightkg: 1.2,
		color: "Brown",
		prevo: "nincada",
		evoLevel: 20,
		eggGroups: ["Mineral"],
	},
	 articuno: {
		num: 144,
		species: "Articuno",
		types: ["Ice", "Flying"],
		gender: "N",
		baseStats: {hp: 90, atk: 85, def: 85, spa: 100, spd: 95, spe: 125},
		abilities: {0: "Pressure", H: "Snow Warning"},
		heightm: 1.7,
		weightkg: 55.4,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	 moltres: {
		num: 146,
		species: "Moltres",
		types: ["Fire", "Flying"],
		gender: "N",
		baseStats: {hp: 90, atk: 100, def: 90, spa: 125, spd: 85, spe: 90},
		abilities: {0: "Pressure", H: "Regenerator"},
		heightm: 2,
		weightkg: 60,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	 mothim: {
		num: 414,
		species: "Mothim",
		types: ["Bug", "Flying"],
		gender: "M",
		baseStats: {hp: 80, atk: 104, def: 50, spa: 104, spd: 70, spe: 85},
		abilities: {0: "Swarm", H: "Tinted Lens"},
		heightm: 0.9,
		weightkg: 23.3,
		color: "Yellow",
		prevo: "burmy",
		evoLevel: 20,
		eggGroups: ["Bug"],
	},
	 wormadam: {
		num: 413,
		species: "Wormadam",
		baseForme: "Plant",
		types: ["Bug", "Grass"],
		gender: "F",
		baseStats: {hp: 120, atk: 49, def: 95, spa: 109, spd: 115, spe: 56},
		abilities: {0: "Anticipation", H: "Harvest"},
		heightm: 0.5,
		weightkg: 6.5,
		color: "Green",
		prevo: "burmy",
		evoLevel: 20,
		eggGroups: ["Bug"],
		otherFormes: ["wormadamsandy", "wormadamtrash"],
	},
	 wormadamsandy: {
		num: 413,
		species: "Wormadam-Sandy",
		baseSpecies: "Wormadam",
		forme: "Sandy",
		formeLetter: "G",
		types: ["Bug", "Ground"],
		gender: "F",
		baseStats: {hp: 90, atk: 100, def: 135, spa: 70, spd: 105, spe: 40},
		abilities: {0: "Anticipation", H: "Prankster"},
		heightm: 0.5,
		weightkg: 6.5,
		color: "Brown",
		prevo: "burmy",
		evoLevel: 20,
		eggGroups: ["Bug"],
		spritenum: 847,
	},
	 wormadamtrash: {
		num: 413,
		species: "Wormadam-Trash",
		baseSpecies: "Wormadam",
		forme: "Trash",
		formeLetter: "S",
		types: ["Bug", "Steel"],
		gender: "F",
		baseStats: {hp: 70, atk: 82, def: 112, spa: 80, spd: 112, spe: 25},
		abilities: {0: "Anticipation", H: "Overcoat"},
		heightm: 0.5,
		weightkg: 6.5,
		color: "Red",
		prevo: "burmy",
		evoLevel: 20,
		eggGroups: ["Bug"],
		spritenum: 848,
	},
  };
