'use strict';

exports.BattlePokedex = {
  charish: {
        num: 736,
        species: "Charish",
        types: ["Fire","Dark"],
        baseStats: {hp: 55, atk: 70, def: 65, spa: 82, spd: 70, spe: 31},
        abilities: {0: "Flare Boost"},
        evos: ["charkol"],
	},
  charkol: {
        num: 324,
        species: "Charkol",
        types: ["Fire","Dark"],
        baseStats: {hp: 90, atk: 112, def: 81, spa: 109, spd: 75, spe: 53},
        abilities: {0: "Fire Resistance"},
	color: "Brown",
	heightm: 0.33,
	weightkg: 102.4,
  },
  sudowoodomega: {
        num: 185,
        species: "Sudowoodo-Mega",
        types: ["Rock"],
        baseStats: {hp: 70, atk: 115, def: 135, spa: 15, spd: 85, spe: 40},
        abilities: {0: "Skill Link"},
        prevo: "Sudowoodo",
  },
  charizardmegaz: {
        num: 6,
        species: "Charizard-Mega-Z",
        types: ["Ground","Fire"],
        baseStats: {hp: 78, atk: 94, def: 118, spa: 99, spd: 135, spe: 96},
        abilities: {0: "Arena Trap"},
        prevo: "Charizard",
  },
  kinglercalibri: {
        num: 99,
        species: "Kingler-Calibri",
        types: ["Rock","Water"],
        baseStats: {hp: 55, atk: 150, def: 100, spa: 105, spd: 100, spe: 30},
        abilities: {0: "Boulder Shield"},
	baseSpecies: "Kingler",
	heightm: 1,
	weightkg: 77,
	color: "Red",
	formeLetter: "C",
  },
  parasectcalibri: {
        num: 47,
        species: "Parasect-Calibri",
        types: ["Bug","Fairy"],
        baseStats: {hp: 60, atk: 100, def: 105, spa: 75, spd: 105, spe: 30},
        abilities: {0: "Powder Eject"},
	baseSpecies: "Parasect",
	heightm: 0.6,
	weightkg: 45,
	color: "Red",
	formeLetter: "C",
  },
  terrakioncalibri: {
        num: 639,
        species: "Terrakion-Calibri",
        types: ["Fighting","Ground"],
        baseStats: {hp: 91, atk: 159, def: 110, spa: 72, spd: 99, spe: 88},
        abilities: {0: "Fighting Stance"},
	baseSpecies: "Terrakion",
	heightm: 0.74,
	weightkg: 196,
	color: "Gray",
	formeLetter: "C",
  },
  tropiusmega: {
        num: 357,
        species: "Tropius-Mega",
	formeLetter: "M",
        types: ["Grass","Flying"],
        baseStats: {hp: 99, atk: 68, def: 93, spa: 72, spd: 97, spe: 131},
        abilities: {0: "Air Lock"},
	prevo: "Tropius",
	baseSpecies: "Tropius",
	heightm: 3.5,
	weightkg: 203,
	color: "Green",
  },
  dinodrill: {
        num: 696,
        species: "Dinodrill",
        types: ["Ground","Steel"],
        baseStats: {hp: 43, atk: 70, def: 70, spa: 41, spd: 30, spe: 83},
        abilities: {0: "Mold Breaker", H: "Solid Rock"},
        evos: ["collosodrill"],
  },
  collosodrill: {
        num: 697,
        species: "Collosodrill",
        types: ["Rock","Steel"],
        baseStats: {hp: 55, atk: 100, def: 99, spa: 67, spd: 80, spe: 100},
        abilities: {0: "Drill Reinforcement"},
	prevo: "dinodrill",  
  },
  
};
