'use strict';

exports.BattlePokedex = {
  charish: {
        num: 736,
        species: "Charish",
        types: ["Fire","Dark"],
        baseStats: {hp: 55, atk: 70, def: 65, spa: 82, spd: 70, spe: 31},
        abilities: {0: "Flare Boost"},
        evos: ["charkol"],
	},
  charkol: {
        num: 324,
        species: "Charkol",
        types: ["Fire","Dark"],
        baseStats: {hp: 90, atk: 112, def: 81, spa: 109, spd: 75, spe: 53},
        abilities: {0: "Fire Resistance"},
        evos: ["Does Not Evolve"],
  },
  calibri: {
        num: 640,
        species: "Calibri",
        types: ["Fighting"],
        baseStats: {hp: 80, atk: 140, def: 85, spa: 40, spd: 100, spe: 40},
        abilities: {0: "Speed Boost"},
        evos: ["Does Not Evolve"],
  },
  sudowoodomega: {
        num: 185,
        species: "Sudowoodo-Mega",
        types: ["Rock"],
        baseStats: {hp: 70, atk: 115, def: 135, spa: 15, spd: 85, spe: 40},
        abilities: {0: "Skill Link"},
        evos: ["Does Not Evolve"],
        prevo: "Sudowoodo",
  },
  charizardmegaz: {
        num: 6,
        species: "Charizard-Mega-Z",
        types: ["Ground","Fire"],
        baseStats: {hp: 78, atk: 94, def: 118, spa: 99, spd: 135, spe: 96},
        abilities: {0: "Arena Trap"},
        evos: ["Does Not Evolve"],
        prevo: "Charizard",
  },
  kingleralola: {
        num: 99,
        species: "Kingler-Alola",
        types: ["Water","Rock"],
        baseStats: {hp: 55, atk: 150, def: 100, spa: 105, spd: 100, spe: 30},
        abilities: {0: "Boulder Shield"},
        evos: ["Does Not Evolve"],
  },
  tropiusmega: {
        num: 357,
        species: "Tropius-Mega",
        types: ["Grass","Flying"],
        baseStats: {hp: 99, atk: 68, def: 93, spa: 72, spd: 97, spe: 131},
        abilities: {0: "Air Lock"},
        evos: ["Does Not Evolve"],
	prevo: "Tropius",
  },
  dinodrill: {
        num: 696,
        species: "Dinodrill",
        types: ["Ground","Steel"],
        baseStats: {hp: 43, atk: 70, def: 70, spa: 41, spd: 30, spe: 83},
        abilities: {0: "Mold Breaker", H: "Solid Rock"},
        evos: ["collosodrill"],
  },
  collosodrill: {
        num: 697,
        species: "Collosodrill",
        types: ["Rock","Steel"],
        baseStats: {hp: 55, atk: 100, def: 99, spa: 67, spd: 80, spe: 100},
        abilities: {0: "Drill Reinforcement"},
        evos: ["Does Not Evolve"],
	prevo: "dinodrill",
  },
  goropix: {
        num: 1000,
        species: "Goropix",
        types: ["Normal"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixfire: {
        num: 1001,
        species: "Goropix-Fire",
        types: ["Fire"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixwater: {
        num: 1002,
        species: "Goropix-Water",
        types: ["Water"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixgrass: {
        num: 1003,
        species: "Goropix-Grass",
        types: ["Grass"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixrock: {
        num: 1004,
        species: "Goropix-Rock",
        types: ["Rock"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixground: {
        num: 1005,
        species: "Goropix-Ground",
        types: ["Ground"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixfairy: {
        num: 1006,
        species: "Goropix-Fairy",
        types: ["Fairy"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixdark: {
        num: 1007,
        species: "Goropix-Dark",
        types: ["Dark"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixghost: {
        num: 1008,
        species: "Goropix-Ghost",
        types: ["Ghost"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixbug: {
        num: 1009,
        species: "Goropix-Bug",
        types: ["Bug"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixpsychic: {
        num: 1010,
        species: "Goropix-Psychic",
        types: ["Psychic"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixdragon: {
        num: 1011,
        species: "Goropix-Dragon",
        types: ["Dragon"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixelectric: {
        num: 1009,
        species: "Goropix-Electric",
        types: ["Electric"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixfighting: {
        num: 1010,
        species: "Goropix-Fighting",
        types: ["Fighting"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixpoison: {
        num: 1011,
        species: "Goropix-Poison",
        types: ["Poison"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  goropixflying: {
        num: 1011,
        species: "Goropix-Flying",
        types: ["Flying"],
        baseStats: {hp: 80, atk: 100, def: 80, spa: 100, spd: 80, spe: 100},
        abilities: {0: "Adaptability"},
        evos: ["Does Not Evolve"],
  },
  
};
